// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avirxhsviwrqtyzcymql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2aXJ4aHN2aXdycXR5emN5bXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NDE1OTIsImV4cCI6MjA1ODIxNzU5Mn0.97sYHwFqp2rEXnCjQr76lItFrshBBPwehKKF0zYdHVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);